image: openjdk:8
pipelines:
  default:
    - step:
        name: Build library
        script:
          - bash ./gradlew build
    - step:
        name: Run Unit tests
        script:
          - bash ./gradlew test