image: dotykacka/java-build-box:latest
pipelines:

  branches:
    master:
      - parallel:
          - step:
              name: Build & tests
              caches:
                - gradle-wrapper
                - gradle
              script:
                - sh ./gradlew build
          - step:
              name: Security Scan
              script:
                - pipe: atlassian/git-secrets-scan:0.4.3
#      - step:
#          name: Publish build artifact
#          deployment: Production artifact
#          caches:
#            - gradle-wrapper
#            - gradle
#          script:
#            - sh ./gradlew jar publish

definitions:
  caches:
    gradle-wrapper: ~/.gradle/wrapper